spring:
  datasource:
    url: jdbc:mysql://localhost:13306/db_account
    username: root
    password: jliang83
    driver-class-name: com.mysql.jdbc.Driver
# 配置mybatis规则、使用MyBatisPlus则此项配置无效
mybatis-plus:
  mapper-locations: classpath:mybatis/mapper/*.xml
  configuration:
    map-underscore-to-camel-case: true
